services:
  payload:
    image: public.ecr.aws/umcai/xc2f/payload:latest
    container_name: payload
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      # 将当前目录映射到容器的 /app
      - .:/app
      # 排除 node_modules，防止跨平台编译冲突
      - /app/node_modules
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    command: postgres -c config_file=/var/lib/postgresql/postgresql.conf
    volumes:
      - pgdata:/var/lib/postgresql
      - ./postgres/postgresql.conf:/var/lib/postgresql/postgresql.conf:ro
      - ./postgres/pg_hba.conf:/var/lib/postgresql/pg_hba.conf:ro
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}

volumes:
  pgdata:
    external: true
    name: xc2f_pgdata
